'Перевод':
  - base-branch: 'translate'

'НЕ МОДУЛЬНО':
  - all: ['code/**']
  - base-branch: 'master220'

'Частичная модульность':
  - all: ['code/**', modular_bandastation/**]
  - base-branch: 'master220'

'TGUI':
  - all: ['tgui/**']

'Звук':
  - all: ['**/*.ogg']

'Спрайты':
  - all: ['**/*.dmi', '**/*.png']

'Изменение Карты':
 - all: ['**/*.dmm']

'Инструменты':
  - all: ['.gihub/workflows/**', 'tools/**']

'Изменение конфига':
  - all: ['config/**']

'Документация':
  - all: ['**/*.md']

'SQL':
  - all: ['SQL/**']
