'TGUI':
  - 'tgui/**'

'Звук':
  - '**/*.ogg'

'Спрайты':
  - '**/*.dmi'
  - '**/*.png'

'Изменение Карты':
  - '**/*.dmm'

'НЕ МОДУЛЬНО':
  - all: ['code/**']
  - branches-ignore:
    - 'translate'

'Частичная модульность':
  - all: ['code/**', modular_bandastation/**]

'Перевод':
  - head-branch: ['translate']

'Инструменты':
  - '.gihub/workflows/**'
  - 'tools/**'

'Изменение конфига':
  - 'config/**'

'Документация':
  - '**/*.md'

'SQL':
  - 'SQL/**'
