- name: Label
  uses: actions/labeler@v5.0.0

on:
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
